// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bookclub.sql

package dbgen

import (
	"context"
	"database/sql"
)

const countSubmissionsByRound = `-- name: CountSubmissionsByRound :one
SELECT COUNT(*) as count FROM submissions WHERE round_id = ?
`

func (q *Queries) CountSubmissionsByRound(ctx context.Context, roundID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubmissionsByRound, roundID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVotesByRound = `-- name: CountVotesByRound :one
SELECT COUNT(*) as count FROM votes WHERE round_id = ?
`

func (q *Queries) CountVotesByRound(ctx context.Context, roundID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVotesByRound, roundID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (title, status, vote_code)
VALUES (?, ?, ?)
RETURNING id, title, status, vote_code, created_at
`

type CreateRoundParams struct {
	Title    string `json:"title"`
	Status   string `json:"status"`
	VoteCode string `json:"vote_code"`
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, createRound, arg.Title, arg.Status, arg.VoteCode)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.VoteCode,
		&i.CreatedAt,
	)
	return i, err
}

const createScheduleEntry = `-- name: CreateScheduleEntry :one
INSERT INTO schedule (round_id, book_title, book_author, suggested_by, meeting_date, reading_progress, status, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, round_id, book_title, book_author, suggested_by, meeting_date, reading_progress, status, notes, created_at
`

type CreateScheduleEntryParams struct {
	RoundID         sql.NullInt64  `json:"round_id"`
	BookTitle       string         `json:"book_title"`
	BookAuthor      string         `json:"book_author"`
	SuggestedBy     sql.NullString `json:"suggested_by"`
	MeetingDate     sql.NullString `json:"meeting_date"`
	ReadingProgress sql.NullString `json:"reading_progress"`
	Status          string         `json:"status"`
	Notes           sql.NullString `json:"notes"`
}

func (q *Queries) CreateScheduleEntry(ctx context.Context, arg CreateScheduleEntryParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createScheduleEntry,
		arg.RoundID,
		arg.BookTitle,
		arg.BookAuthor,
		arg.SuggestedBy,
		arg.MeetingDate,
		arg.ReadingProgress,
		arg.Status,
		arg.Notes,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookTitle,
		&i.BookAuthor,
		&i.SuggestedBy,
		&i.MeetingDate,
		&i.ReadingProgress,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (round_id, nickname, book_title, book_author, discord_user_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, round_id, nickname, book_title, book_author, discord_user_id, created_at
`

type CreateSubmissionParams struct {
	RoundID       int64          `json:"round_id"`
	Nickname      string         `json:"nickname"`
	BookTitle     string         `json:"book_title"`
	BookAuthor    string         `json:"book_author"`
	DiscordUserID sql.NullString `json:"discord_user_id"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, createSubmission,
		arg.RoundID,
		arg.Nickname,
		arg.BookTitle,
		arg.BookAuthor,
		arg.DiscordUserID,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.Nickname,
		&i.BookTitle,
		&i.BookAuthor,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createVote = `-- name: CreateVote :one
INSERT INTO votes (round_id, nickname, discord_user_id)
VALUES (?, ?, ?)
RETURNING id, round_id, nickname, discord_user_id, created_at
`

type CreateVoteParams struct {
	RoundID       int64          `json:"round_id"`
	Nickname      string         `json:"nickname"`
	DiscordUserID sql.NullString `json:"discord_user_id"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, createVote, arg.RoundID, arg.Nickname, arg.DiscordUserID)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.Nickname,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createVoteRanking = `-- name: CreateVoteRanking :exec
INSERT INTO vote_rankings (vote_id, submission_id, rank)
VALUES (?, ?, ?)
`

type CreateVoteRankingParams struct {
	VoteID       int64 `json:"vote_id"`
	SubmissionID int64 `json:"submission_id"`
	Rank         int64 `json:"rank"`
}

func (q *Queries) CreateVoteRanking(ctx context.Context, arg CreateVoteRankingParams) error {
	_, err := q.db.ExecContext(ctx, createVoteRanking, arg.VoteID, arg.SubmissionID, arg.Rank)
	return err
}

const deleteScheduleEntry = `-- name: DeleteScheduleEntry :exec
DELETE FROM schedule WHERE id = ?
`

func (q *Queries) DeleteScheduleEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleEntry, id)
	return err
}

const deleteSubmission = `-- name: DeleteSubmission :exec
DELETE FROM submissions WHERE id = ?
`

func (q *Queries) DeleteSubmission(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubmission, id)
	return err
}

const deleteVoteRankings = `-- name: DeleteVoteRankings :exec
DELETE FROM vote_rankings WHERE vote_id = ?
`

func (q *Queries) DeleteVoteRankings(ctx context.Context, voteID int64) error {
	_, err := q.db.ExecContext(ctx, deleteVoteRankings, voteID)
	return err
}

const getConfig = `-- name: GetConfig :one
SELECT "key", value, created_at FROM config WHERE key = ? LIMIT 1
`

func (q *Queries) GetConfig(ctx context.Context, key string) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var i Config
	err := row.Scan(&i.Key, &i.Value, &i.CreatedAt)
	return i, err
}

const getCurrentReading = `-- name: GetCurrentReading :one
SELECT id, round_id, book_title, book_author, suggested_by, meeting_date, reading_progress, status, notes, created_at FROM schedule WHERE status = 'reading' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetCurrentReading(ctx context.Context) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getCurrentReading)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookTitle,
		&i.BookAuthor,
		&i.SuggestedBy,
		&i.MeetingDate,
		&i.ReadingProgress,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentRound = `-- name: GetCurrentRound :one
SELECT id, title, status, vote_code, created_at FROM rounds 
WHERE status IN ('submissions_open', 'voting_open')
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetCurrentRound(ctx context.Context) (Round, error) {
	row := q.db.QueryRowContext(ctx, getCurrentRound)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.VoteCode,
		&i.CreatedAt,
	)
	return i, err
}

const getNextUpcoming = `-- name: GetNextUpcoming :one
SELECT id, round_id, book_title, book_author, suggested_by, meeting_date, reading_progress, status, notes, created_at FROM schedule WHERE status = 'upcoming' ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetNextUpcoming(ctx context.Context) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getNextUpcoming)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookTitle,
		&i.BookAuthor,
		&i.SuggestedBy,
		&i.MeetingDate,
		&i.ReadingProgress,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getRound = `-- name: GetRound :one
SELECT id, title, status, vote_code, created_at FROM rounds WHERE id = ? LIMIT 1
`

func (q *Queries) GetRound(ctx context.Context, id int64) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.VoteCode,
		&i.CreatedAt,
	)
	return i, err
}

const getRoundByVoteCode = `-- name: GetRoundByVoteCode :one
SELECT id, title, status, vote_code, created_at FROM rounds WHERE vote_code = ? LIMIT 1
`

func (q *Queries) GetRoundByVoteCode(ctx context.Context, voteCode string) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRoundByVoteCode, voteCode)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.VoteCode,
		&i.CreatedAt,
	)
	return i, err
}

const getScheduleEntry = `-- name: GetScheduleEntry :one
SELECT id, round_id, book_title, book_author, suggested_by, meeting_date, reading_progress, status, notes, created_at FROM schedule WHERE id = ? LIMIT 1
`

func (q *Queries) GetScheduleEntry(ctx context.Context, id int64) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleEntry, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookTitle,
		&i.BookAuthor,
		&i.SuggestedBy,
		&i.MeetingDate,
		&i.ReadingProgress,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT id, round_id, nickname, book_title, book_author, discord_user_id, created_at FROM submissions WHERE id = ? LIMIT 1
`

func (q *Queries) GetSubmission(ctx context.Context, id int64) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.Nickname,
		&i.BookTitle,
		&i.BookAuthor,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionByNickname = `-- name: GetSubmissionByNickname :one
SELECT id, round_id, nickname, book_title, book_author, discord_user_id, created_at FROM submissions WHERE round_id = ? AND nickname = ? LIMIT 1
`

type GetSubmissionByNicknameParams struct {
	RoundID  int64  `json:"round_id"`
	Nickname string `json:"nickname"`
}

func (q *Queries) GetSubmissionByNickname(ctx context.Context, arg GetSubmissionByNicknameParams) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionByNickname, arg.RoundID, arg.Nickname)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.Nickname,
		&i.BookTitle,
		&i.BookAuthor,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getVote = `-- name: GetVote :one
SELECT id, round_id, nickname, discord_user_id, created_at FROM votes WHERE id = ? LIMIT 1
`

func (q *Queries) GetVote(ctx context.Context, id int64) (Vote, error) {
	row := q.db.QueryRowContext(ctx, getVote, id)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.Nickname,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteByNickname = `-- name: GetVoteByNickname :one
SELECT id, round_id, nickname, discord_user_id, created_at FROM votes WHERE round_id = ? AND nickname = ? LIMIT 1
`

type GetVoteByNicknameParams struct {
	RoundID  int64  `json:"round_id"`
	Nickname string `json:"nickname"`
}

func (q *Queries) GetVoteByNickname(ctx context.Context, arg GetVoteByNicknameParams) (Vote, error) {
	row := q.db.QueryRowContext(ctx, getVoteByNickname, arg.RoundID, arg.Nickname)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.Nickname,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listAllRankingsByRound = `-- name: ListAllRankingsByRound :many
SELECT vr.id, vr.vote_id, vr.submission_id, vr.rank FROM vote_rankings vr
JOIN votes v ON vr.vote_id = v.id
WHERE v.round_id = ?
ORDER BY v.id, vr.rank ASC
`

func (q *Queries) ListAllRankingsByRound(ctx context.Context, roundID int64) ([]VoteRanking, error) {
	rows, err := q.db.QueryContext(ctx, listAllRankingsByRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoteRanking{}
	for rows.Next() {
		var i VoteRanking
		if err := rows.Scan(
			&i.ID,
			&i.VoteID,
			&i.SubmissionID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSubmissions = `-- name: ListAllSubmissions :many
SELECT s.id, s.round_id, s.nickname, s.book_title, s.book_author, s.discord_user_id, s.created_at, r.title as round_title, r.status as round_status
FROM submissions s
JOIN rounds r ON s.round_id = r.id
ORDER BY s.created_at DESC
`

type ListAllSubmissionsRow struct {
	ID            int64          `json:"id"`
	RoundID       int64          `json:"round_id"`
	Nickname      string         `json:"nickname"`
	BookTitle     string         `json:"book_title"`
	BookAuthor    string         `json:"book_author"`
	DiscordUserID sql.NullString `json:"discord_user_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	RoundTitle    string         `json:"round_title"`
	RoundStatus   string         `json:"round_status"`
}

func (q *Queries) ListAllSubmissions(ctx context.Context) ([]ListAllSubmissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSubmissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSubmissionsRow{}
	for rows.Next() {
		var i ListAllSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.Nickname,
			&i.BookTitle,
			&i.BookAuthor,
			&i.DiscordUserID,
			&i.CreatedAt,
			&i.RoundTitle,
			&i.RoundStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankingsByVote = `-- name: ListRankingsByVote :many
SELECT id, vote_id, submission_id, rank FROM vote_rankings WHERE vote_id = ? ORDER BY rank ASC
`

func (q *Queries) ListRankingsByVote(ctx context.Context, voteID int64) ([]VoteRanking, error) {
	rows, err := q.db.QueryContext(ctx, listRankingsByVote, voteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoteRanking{}
	for rows.Next() {
		var i VoteRanking
		if err := rows.Scan(
			&i.ID,
			&i.VoteID,
			&i.SubmissionID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRounds = `-- name: ListRounds :many
SELECT id, title, status, vote_code, created_at FROM rounds ORDER BY created_at DESC
`

func (q *Queries) ListRounds(ctx context.Context) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, listRounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Round{}
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.VoteCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedule = `-- name: ListSchedule :many
SELECT id, round_id, book_title, book_author, suggested_by, meeting_date, reading_progress, status, notes, created_at FROM schedule ORDER BY 
    CASE status
        WHEN 'reading' THEN 1
        WHEN 'upcoming' THEN 2
        WHEN 'completed' THEN 3
    END,
    created_at DESC
`

func (q *Queries) ListSchedule(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.BookTitle,
			&i.BookAuthor,
			&i.SuggestedBy,
			&i.MeetingDate,
			&i.ReadingProgress,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByRound = `-- name: ListSubmissionsByRound :many
SELECT id, round_id, nickname, book_title, book_author, discord_user_id, created_at FROM submissions WHERE round_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListSubmissionsByRound(ctx context.Context, roundID int64) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Submission{}
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.Nickname,
			&i.BookTitle,
			&i.BookAuthor,
			&i.DiscordUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesByRound = `-- name: ListVotesByRound :many
SELECT id, round_id, nickname, discord_user_id, created_at FROM votes WHERE round_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListVotesByRound(ctx context.Context, roundID int64) ([]Vote, error) {
	rows, err := q.db.QueryContext(ctx, listVotesByRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vote{}
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.Nickname,
			&i.DiscordUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO config (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.Key, arg.Value)
	return err
}

const updateRoundStatus = `-- name: UpdateRoundStatus :exec
UPDATE rounds SET status = ? WHERE id = ?
`

type UpdateRoundStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateRoundStatus(ctx context.Context, arg UpdateRoundStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRoundStatus, arg.Status, arg.ID)
	return err
}

const updateScheduleEntry = `-- name: UpdateScheduleEntry :exec
UPDATE schedule 
SET book_title = ?, book_author = ?, suggested_by = ?, meeting_date = ?, reading_progress = ?, status = ?, notes = ?
WHERE id = ?
`

type UpdateScheduleEntryParams struct {
	BookTitle       string         `json:"book_title"`
	BookAuthor      string         `json:"book_author"`
	SuggestedBy     sql.NullString `json:"suggested_by"`
	MeetingDate     sql.NullString `json:"meeting_date"`
	ReadingProgress sql.NullString `json:"reading_progress"`
	Status          string         `json:"status"`
	Notes           sql.NullString `json:"notes"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateScheduleEntry(ctx context.Context, arg UpdateScheduleEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleEntry,
		arg.BookTitle,
		arg.BookAuthor,
		arg.SuggestedBy,
		arg.MeetingDate,
		arg.ReadingProgress,
		arg.Status,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateScheduleProgress = `-- name: UpdateScheduleProgress :exec
UPDATE schedule SET reading_progress = ? WHERE id = ?
`

type UpdateScheduleProgressParams struct {
	ReadingProgress sql.NullString `json:"reading_progress"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateScheduleProgress(ctx context.Context, arg UpdateScheduleProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleProgress, arg.ReadingProgress, arg.ID)
	return err
}

const updateSubmission = `-- name: UpdateSubmission :exec
UPDATE submissions
SET book_title = ?, book_author = ?, nickname = ?
WHERE id = ?
`

type UpdateSubmissionParams struct {
	BookTitle  string `json:"book_title"`
	BookAuthor string `json:"book_author"`
	Nickname   string `json:"nickname"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, updateSubmission,
		arg.BookTitle,
		arg.BookAuthor,
		arg.Nickname,
		arg.ID,
	)
	return err
}
