// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"time"
)

type Config struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Round struct {
	ID        int64        `json:"id"`
	Title     string       `json:"title"`
	Status    string       `json:"status"`
	VoteCode  string       `json:"vote_code"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Schedule struct {
	ID              int64          `json:"id"`
	RoundID         sql.NullInt64  `json:"round_id"`
	BookTitle       string         `json:"book_title"`
	BookAuthor      string         `json:"book_author"`
	SuggestedBy     sql.NullString `json:"suggested_by"`
	MeetingDate     sql.NullString `json:"meeting_date"`
	ReadingProgress sql.NullString `json:"reading_progress"`
	Status          string         `json:"status"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Submission struct {
	ID            int64          `json:"id"`
	RoundID       int64          `json:"round_id"`
	Nickname      string         `json:"nickname"`
	BookTitle     string         `json:"book_title"`
	BookAuthor    string         `json:"book_author"`
	DiscordUserID sql.NullString `json:"discord_user_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}

type Vote struct {
	ID            int64          `json:"id"`
	RoundID       int64          `json:"round_id"`
	Nickname      string         `json:"nickname"`
	DiscordUserID sql.NullString `json:"discord_user_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type VoteRanking struct {
	ID           int64 `json:"id"`
	VoteID       int64 `json:"vote_id"`
	SubmissionID int64 `json:"submission_id"`
	Rank         int64 `json:"rank"`
}
