// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"database/sql"
	"time"
)

type Book struct {
	ID             int64          `json:"id"`
	Title          string         `json:"title"`
	Author         string         `json:"author"`
	Submitter      sql.NullString `json:"submitter"`
	Pitch          sql.NullString `json:"pitch"`
	Tags           sql.NullString `json:"tags"`
	PageCount      sql.NullInt64  `json:"page_count"`
	Description    sql.NullString `json:"description"`
	ContentNotes   sql.NullString `json:"content_notes"`
	CoverUrl       sql.NullString `json:"cover_url"`
	Isbn           sql.NullString `json:"isbn"`
	MetadataSource sql.NullString `json:"metadata_source"`
	MetadataID     sql.NullString `json:"metadata_id"`
	Status         string         `json:"status"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Config struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Round struct {
	ID        int64        `json:"id"`
	Title     string       `json:"title"`
	Status    string       `json:"status"`
	VoteCode  string       `json:"vote_code"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type RoundEntry struct {
	ID      int64          `json:"id"`
	RoundID int64          `json:"round_id"`
	BookID  int64          `json:"book_id"`
	AddedBy sql.NullString `json:"added_by"`
	AddedAt sql.NullTime   `json:"added_at"`
}

type RoundResult struct {
	ID          int64          `json:"id"`
	RoundID     int64          `json:"round_id"`
	BookID      sql.NullInt64  `json:"book_id"`
	ResultType  string         `json:"result_type"`
	SelectedBy  sql.NullString `json:"selected_by"`
	SelectedAt  sql.NullTime   `json:"selected_at"`
	Confirmed   int64          `json:"confirmed"`
	ConfirmedBy sql.NullString `json:"confirmed_by"`
	ConfirmedAt sql.NullTime   `json:"confirmed_at"`
}

type Schedule struct {
	ID              int64          `json:"id"`
	RoundID         sql.NullInt64  `json:"round_id"`
	BookTitle       string         `json:"book_title"`
	BookAuthor      string         `json:"book_author"`
	SuggestedBy     sql.NullString `json:"suggested_by"`
	MeetingDate     sql.NullString `json:"meeting_date"`
	ReadingProgress sql.NullString `json:"reading_progress"`
	Status          string         `json:"status"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	TotalChapters   sql.NullInt64  `json:"total_chapters"`
	CoverUrl        sql.NullString `json:"cover_url"`
}

type Submission struct {
	ID            int64          `json:"id"`
	RoundID       int64          `json:"round_id"`
	Nickname      string         `json:"nickname"`
	BookTitle     string         `json:"book_title"`
	BookAuthor    string         `json:"book_author"`
	DiscordUserID sql.NullString `json:"discord_user_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}

type Vote struct {
	ID            int64          `json:"id"`
	RoundID       int64          `json:"round_id"`
	Nickname      string         `json:"nickname"`
	DiscordUserID sql.NullString `json:"discord_user_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type VoteRanking struct {
	ID           int64 `json:"id"`
	VoteID       int64 `json:"vote_id"`
	SubmissionID int64 `json:"submission_id"`
	Rank         int64 `json:"rank"`
}

type ReadingWeek struct {
	ID             int64          `json:"id"`
	ScheduleID     int64          `json:"schedule_id"`
	WeekNumber     int64          `json:"week_number"`
	WeekLabel      sql.NullString `json:"week_label"`
	StartChapter   sql.NullString `json:"start_chapter"`
	EndChapter     sql.NullString `json:"end_chapter"`
	Notes          sql.NullString `json:"notes"`
	DiscussionDate sql.NullString `json:"discussion_date"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Checkin struct {
	ID         int64          `json:"id"`
	ScheduleID int64          `json:"schedule_id"`
	Nickname   string         `json:"nickname"`
	WeekNumber int64          `json:"week_number"`
	Emoji      sql.NullString `json:"emoji"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}
