// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: progress.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createReadingWeek = `-- name: CreateReadingWeek :one
INSERT INTO reading_weeks (schedule_id, week_number, week_label, start_chapter, end_chapter, notes, discussion_date)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, schedule_id, week_number, week_label, start_chapter, end_chapter, notes, discussion_date, created_at
`

type CreateReadingWeekParams struct {
	ScheduleID     int64          `json:"schedule_id"`
	WeekNumber     int64          `json:"week_number"`
	WeekLabel      sql.NullString `json:"week_label"`
	StartChapter   sql.NullString `json:"start_chapter"`
	EndChapter     sql.NullString `json:"end_chapter"`
	Notes          sql.NullString `json:"notes"`
	DiscussionDate sql.NullString `json:"discussion_date"`
}

func (q *Queries) CreateReadingWeek(ctx context.Context, arg CreateReadingWeekParams) (ReadingWeek, error) {
	row := q.db.QueryRowContext(ctx, createReadingWeek,
		arg.ScheduleID,
		arg.WeekNumber,
		arg.WeekLabel,
		arg.StartChapter,
		arg.EndChapter,
		arg.Notes,
		arg.DiscussionDate,
	)
	var i ReadingWeek
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.WeekNumber,
		&i.WeekLabel,
		&i.StartChapter,
		&i.EndChapter,
		&i.Notes,
		&i.DiscussionDate,
		&i.CreatedAt,
	)
	return i, err
}

const getReadingWeek = `-- name: GetReadingWeek :one
SELECT id, schedule_id, week_number, week_label, start_chapter, end_chapter, notes, discussion_date, created_at FROM reading_weeks WHERE id = ? LIMIT 1
`

func (q *Queries) GetReadingWeek(ctx context.Context, id int64) (ReadingWeek, error) {
	row := q.db.QueryRowContext(ctx, getReadingWeek, id)
	var i ReadingWeek
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.WeekNumber,
		&i.WeekLabel,
		&i.StartChapter,
		&i.EndChapter,
		&i.Notes,
		&i.DiscussionDate,
		&i.CreatedAt,
	)
	return i, err
}

const listReadingWeeks = `-- name: ListReadingWeeks :many
SELECT id, schedule_id, week_number, week_label, start_chapter, end_chapter, notes, discussion_date, created_at FROM reading_weeks WHERE schedule_id = ? ORDER BY week_number ASC
`

func (q *Queries) ListReadingWeeks(ctx context.Context, scheduleID int64) ([]ReadingWeek, error) {
	rows, err := q.db.QueryContext(ctx, listReadingWeeks, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingWeek{}
	for rows.Next() {
		var i ReadingWeek
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.WeekNumber,
			&i.WeekLabel,
			&i.StartChapter,
			&i.EndChapter,
			&i.Notes,
			&i.DiscussionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReadingWeek = `-- name: UpdateReadingWeek :exec
UPDATE reading_weeks SET week_label = ?, start_chapter = ?, end_chapter = ?, notes = ?, discussion_date = ?
WHERE id = ?
`

type UpdateReadingWeekParams struct {
	WeekLabel      sql.NullString `json:"week_label"`
	StartChapter   sql.NullString `json:"start_chapter"`
	EndChapter     sql.NullString `json:"end_chapter"`
	Notes          sql.NullString `json:"notes"`
	DiscussionDate sql.NullString `json:"discussion_date"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateReadingWeek(ctx context.Context, arg UpdateReadingWeekParams) error {
	_, err := q.db.ExecContext(ctx, updateReadingWeek,
		arg.WeekLabel,
		arg.StartChapter,
		arg.EndChapter,
		arg.Notes,
		arg.DiscussionDate,
		arg.ID,
	)
	return err
}

const deleteReadingWeek = `-- name: DeleteReadingWeek :exec
DELETE FROM reading_weeks WHERE id = ?
`

func (q *Queries) DeleteReadingWeek(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReadingWeek, id)
	return err
}

const getLatestWeek = `-- name: GetLatestWeek :one
SELECT id, schedule_id, week_number, week_label, start_chapter, end_chapter, notes, discussion_date, created_at FROM reading_weeks WHERE schedule_id = ? ORDER BY week_number DESC LIMIT 1
`

func (q *Queries) GetLatestWeek(ctx context.Context, scheduleID int64) (ReadingWeek, error) {
	row := q.db.QueryRowContext(ctx, getLatestWeek, scheduleID)
	var i ReadingWeek
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.WeekNumber,
		&i.WeekLabel,
		&i.StartChapter,
		&i.EndChapter,
		&i.Notes,
		&i.DiscussionDate,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCheckin = `-- name: UpsertCheckin :exec
INSERT INTO checkins (schedule_id, nickname, week_number, emoji)
VALUES (?, ?, ?, ?)
ON CONFLICT(schedule_id, nickname, week_number) DO UPDATE SET emoji = excluded.emoji
`

type UpsertCheckinParams struct {
	ScheduleID int64  `json:"schedule_id"`
	Nickname   string `json:"nickname"`
	WeekNumber int64  `json:"week_number"`
	Emoji      string `json:"emoji"`
}

func (q *Queries) UpsertCheckin(ctx context.Context, arg UpsertCheckinParams) error {
	_, err := q.db.ExecContext(ctx, upsertCheckin, arg.ScheduleID, arg.Nickname, arg.WeekNumber, arg.Emoji)
	return err
}

const listCheckinsByWeek = `-- name: ListCheckinsByWeek :many
SELECT id, schedule_id, nickname, week_number, emoji, created_at FROM checkins WHERE schedule_id = ? AND week_number = ? ORDER BY created_at ASC
`

func (q *Queries) ListCheckinsByWeek(ctx context.Context, scheduleID int64, weekNumber int64) ([]Checkin, error) {
	rows, err := q.db.QueryContext(ctx, listCheckinsByWeek, scheduleID, weekNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkin{}
	for rows.Next() {
		var i Checkin
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.Nickname,
			&i.WeekNumber,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckinsBySchedule = `-- name: ListCheckinsBySchedule :many
SELECT id, schedule_id, nickname, week_number, emoji, created_at FROM checkins WHERE schedule_id = ? ORDER BY week_number ASC, created_at ASC
`

func (q *Queries) ListCheckinsBySchedule(ctx context.Context, scheduleID int64) ([]Checkin, error) {
	rows, err := q.db.QueryContext(ctx, listCheckinsBySchedule, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkin{}
	for rows.Next() {
		var i Checkin
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.Nickname,
			&i.WeekNumber,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCheckinsByWeek = `-- name: CountCheckinsByWeek :one
SELECT COUNT(*) as count FROM checkins WHERE schedule_id = ? AND week_number = ?
`

func (q *Queries) CountCheckinsByWeek(ctx context.Context, scheduleID int64, weekNumber int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCheckinsByWeek, scheduleID, weekNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCheckin = `-- name: DeleteCheckin :exec
DELETE FROM checkins WHERE schedule_id = ? AND nickname = ? AND week_number = ?
`

func (q *Queries) DeleteCheckin(ctx context.Context, scheduleID int64, nickname string, weekNumber int64) error {
	_, err := q.db.ExecContext(ctx, deleteCheckin, scheduleID, nickname, weekNumber)
	return err
}
