// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: v0.2.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addBookToRound = `-- name: AddBookToRound :one

INSERT INTO round_entries (round_id, book_id, added_by)
VALUES (?, ?, ?)
RETURNING id, round_id, book_id, added_by, added_at
`

type AddBookToRoundParams struct {
	RoundID int64          `json:"round_id"`
	BookID  int64          `json:"book_id"`
	AddedBy sql.NullString `json:"added_by"`
}

// Round Entries
func (q *Queries) AddBookToRound(ctx context.Context, arg AddBookToRoundParams) (RoundEntry, error) {
	row := q.db.QueryRowContext(ctx, addBookToRound, arg.RoundID, arg.BookID, arg.AddedBy)
	var i RoundEntry
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookID,
		&i.AddedBy,
		&i.AddedAt,
	)
	return i, err
}

const archiveBook = `-- name: ArchiveBook :exec
UPDATE books SET status = 'archived', deleted_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) ArchiveBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, archiveBook, id)
	return err
}

const confirmResult = `-- name: ConfirmResult :exec
UPDATE round_results
SET confirmed = 1, confirmed_by = ?, confirmed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type ConfirmResultParams struct {
	ConfirmedBy sql.NullString `json:"confirmed_by"`
	ID          int64          `json:"id"`
}

func (q *Queries) ConfirmResult(ctx context.Context, arg ConfirmResultParams) error {
	_, err := q.db.ExecContext(ctx, confirmResult, arg.ConfirmedBy, arg.ID)
	return err
}

const countBooks = `-- name: CountBooks :one
SELECT COUNT(*) as count FROM books WHERE deleted_at IS NULL
`

func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoundEntries = `-- name: CountRoundEntries :one
SELECT COUNT(*) as count FROM round_entries WHERE round_id = ?
`

func (q *Queries) CountRoundEntries(ctx context.Context, roundID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoundEntries, roundID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :one

INSERT INTO books (title, author, submitter, pitch, tags, page_count, description, content_notes, cover_url, isbn, metadata_source, metadata_id, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, author, submitter, pitch, tags, page_count, description, content_notes, cover_url, isbn, metadata_source, metadata_id, status, deleted_at, created_at
`

type CreateBookParams struct {
	Title          string         `json:"title"`
	Author         string         `json:"author"`
	Submitter      sql.NullString `json:"submitter"`
	Pitch          sql.NullString `json:"pitch"`
	Tags           sql.NullString `json:"tags"`
	PageCount      sql.NullInt64  `json:"page_count"`
	Description    sql.NullString `json:"description"`
	ContentNotes   sql.NullString `json:"content_notes"`
	CoverUrl       sql.NullString `json:"cover_url"`
	Isbn           sql.NullString `json:"isbn"`
	MetadataSource sql.NullString `json:"metadata_source"`
	MetadataID     sql.NullString `json:"metadata_id"`
	Status         string         `json:"status"`
}

// Books (library)
func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.Submitter,
		arg.Pitch,
		arg.Tags,
		arg.PageCount,
		arg.Description,
		arg.ContentNotes,
		arg.CoverUrl,
		arg.Isbn,
		arg.MetadataSource,
		arg.MetadataID,
		arg.Status,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Submitter,
		&i.Pitch,
		&i.Tags,
		&i.PageCount,
		&i.Description,
		&i.ContentNotes,
		&i.CoverUrl,
		&i.Isbn,
		&i.MetadataSource,
		&i.MetadataID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRoundResult = `-- name: CreateRoundResult :one

INSERT INTO round_results (round_id, book_id, result_type, selected_by)
VALUES (?, ?, ?, ?)
RETURNING id, round_id, book_id, result_type, selected_by, selected_at, confirmed, confirmed_by, confirmed_at
`

type CreateRoundResultParams struct {
	RoundID    int64          `json:"round_id"`
	BookID     sql.NullInt64  `json:"book_id"`
	ResultType string         `json:"result_type"`
	SelectedBy sql.NullString `json:"selected_by"`
}

// Round Results
func (q *Queries) CreateRoundResult(ctx context.Context, arg CreateRoundResultParams) (RoundResult, error) {
	row := q.db.QueryRowContext(ctx, createRoundResult,
		arg.RoundID,
		arg.BookID,
		arg.ResultType,
		arg.SelectedBy,
	)
	var i RoundResult
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookID,
		&i.ResultType,
		&i.SelectedBy,
		&i.SelectedAt,
		&i.Confirmed,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
	)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, submitter, pitch, tags, page_count, description, content_notes, cover_url, isbn, metadata_source, metadata_id, status, deleted_at, created_at FROM books WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Submitter,
		&i.Pitch,
		&i.Tags,
		&i.PageCount,
		&i.Description,
		&i.ContentNotes,
		&i.CoverUrl,
		&i.Isbn,
		&i.MetadataSource,
		&i.MetadataID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConfirmedResult = `-- name: GetConfirmedResult :one
SELECT id, round_id, book_id, result_type, selected_by, selected_at, confirmed, confirmed_by, confirmed_at FROM round_results WHERE round_id = ? AND confirmed = 1 ORDER BY confirmed_at DESC LIMIT 1
`

func (q *Queries) GetConfirmedResult(ctx context.Context, roundID int64) (RoundResult, error) {
	row := q.db.QueryRowContext(ctx, getConfirmedResult, roundID)
	var i RoundResult
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookID,
		&i.ResultType,
		&i.SelectedBy,
		&i.SelectedAt,
		&i.Confirmed,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
	)
	return i, err
}

const getCurrentBook = `-- name: GetCurrentBook :one
SELECT b.id, b.title, b.author, b.submitter, b.pitch, b.tags, b.page_count, b.description, b.content_notes, b.cover_url, b.isbn, b.metadata_source, b.metadata_id, b.status, b.deleted_at, b.created_at
FROM round_results rr
JOIN books b ON rr.book_id = b.id
WHERE rr.confirmed = 1
ORDER BY rr.confirmed_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentBook(ctx context.Context) (Book, error) {
	row := q.db.QueryRowContext(ctx, getCurrentBook)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Submitter,
		&i.Pitch,
		&i.Tags,
		&i.PageCount,
		&i.Description,
		&i.ContentNotes,
		&i.CoverUrl,
		&i.Isbn,
		&i.MetadataSource,
		&i.MetadataID,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRoundResult = `-- name: GetLatestRoundResult :one
SELECT id, round_id, book_id, result_type, selected_by, selected_at, confirmed, confirmed_by, confirmed_at FROM round_results WHERE round_id = ? ORDER BY selected_at DESC LIMIT 1
`

func (q *Queries) GetLatestRoundResult(ctx context.Context, roundID int64) (RoundResult, error) {
	row := q.db.QueryRowContext(ctx, getLatestRoundResult, roundID)
	var i RoundResult
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookID,
		&i.ResultType,
		&i.SelectedBy,
		&i.SelectedAt,
		&i.Confirmed,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
	)
	return i, err
}

const getRoundEntry = `-- name: GetRoundEntry :one
SELECT id, round_id, book_id, added_by, added_at FROM round_entries WHERE round_id = ? AND book_id = ? LIMIT 1
`

type GetRoundEntryParams struct {
	RoundID int64 `json:"round_id"`
	BookID  int64 `json:"book_id"`
}

func (q *Queries) GetRoundEntry(ctx context.Context, arg GetRoundEntryParams) (RoundEntry, error) {
	row := q.db.QueryRowContext(ctx, getRoundEntry, arg.RoundID, arg.BookID)
	var i RoundEntry
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.BookID,
		&i.AddedBy,
		&i.AddedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, submitter, pitch, tags, page_count, description, content_notes, cover_url, isbn, metadata_source, metadata_id, status, deleted_at, created_at FROM books WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Submitter,
			&i.Pitch,
			&i.Tags,
			&i.PageCount,
			&i.Description,
			&i.ContentNotes,
			&i.CoverUrl,
			&i.Isbn,
			&i.MetadataSource,
			&i.MetadataID,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByStatus = `-- name: ListBooksByStatus :many
SELECT id, title, author, submitter, pitch, tags, page_count, description, content_notes, cover_url, isbn, metadata_source, metadata_id, status, deleted_at, created_at FROM books WHERE status = ? AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListBooksByStatus(ctx context.Context, status string) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Submitter,
			&i.Pitch,
			&i.Tags,
			&i.PageCount,
			&i.Description,
			&i.ContentNotes,
			&i.CoverUrl,
			&i.Isbn,
			&i.MetadataSource,
			&i.MetadataID,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoundEntries = `-- name: ListRoundEntries :many
SELECT b.id, b.title, b.author, b.submitter, b.pitch, b.tags, b.page_count, b.description, b.content_notes, b.cover_url, b.isbn, b.metadata_source, b.metadata_id, b.status, b.deleted_at, b.created_at, re.added_by as entry_added_by, re.added_at as entry_added_at
FROM round_entries re
JOIN books b ON re.book_id = b.id
WHERE re.round_id = ? AND b.deleted_at IS NULL
ORDER BY re.added_at ASC
`

type ListRoundEntriesRow struct {
	ID             int64          `json:"id"`
	Title          string         `json:"title"`
	Author         string         `json:"author"`
	Submitter      sql.NullString `json:"submitter"`
	Pitch          sql.NullString `json:"pitch"`
	Tags           sql.NullString `json:"tags"`
	PageCount      sql.NullInt64  `json:"page_count"`
	Description    sql.NullString `json:"description"`
	ContentNotes   sql.NullString `json:"content_notes"`
	CoverUrl       sql.NullString `json:"cover_url"`
	Isbn           sql.NullString `json:"isbn"`
	MetadataSource sql.NullString `json:"metadata_source"`
	MetadataID     sql.NullString `json:"metadata_id"`
	Status         string         `json:"status"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	EntryAddedBy   sql.NullString `json:"entry_added_by"`
	EntryAddedAt   sql.NullTime   `json:"entry_added_at"`
}

func (q *Queries) ListRoundEntries(ctx context.Context, roundID int64) ([]ListRoundEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoundEntries, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoundEntriesRow{}
	for rows.Next() {
		var i ListRoundEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Submitter,
			&i.Pitch,
			&i.Tags,
			&i.PageCount,
			&i.Description,
			&i.ContentNotes,
			&i.CoverUrl,
			&i.Isbn,
			&i.MetadataSource,
			&i.MetadataID,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.EntryAddedBy,
			&i.EntryAddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoundResults = `-- name: ListRoundResults :many
SELECT id, round_id, book_id, result_type, selected_by, selected_at, confirmed, confirmed_by, confirmed_at FROM round_results WHERE round_id = ? ORDER BY selected_at DESC
`

func (q *Queries) ListRoundResults(ctx context.Context, roundID int64) ([]RoundResult, error) {
	rows, err := q.db.QueryContext(ctx, listRoundResults, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoundResult{}
	for rows.Next() {
		var i RoundResult
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.BookID,
			&i.ResultType,
			&i.SelectedBy,
			&i.SelectedAt,
			&i.Confirmed,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookFromRound = `-- name: RemoveBookFromRound :exec
DELETE FROM round_entries WHERE round_id = ? AND book_id = ?
`

type RemoveBookFromRoundParams struct {
	RoundID int64 `json:"round_id"`
	BookID  int64 `json:"book_id"`
}

func (q *Queries) RemoveBookFromRound(ctx context.Context, arg RemoveBookFromRoundParams) error {
	_, err := q.db.ExecContext(ctx, removeBookFromRound, arg.RoundID, arg.BookID)
	return err
}

const searchBooks = `-- name: SearchBooks :many
SELECT id, title, author, submitter, pitch, tags, page_count, description, content_notes, cover_url, isbn, metadata_source, metadata_id, status, deleted_at, created_at FROM books
WHERE deleted_at IS NULL
  AND (title LIKE '%' || ? || '%' OR author LIKE '%' || ? || '%' OR tags LIKE '%' || ? || '%')
ORDER BY created_at DESC
`

type SearchBooksParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
	Column3 sql.NullString `json:"column_3"`
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, searchBooks, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Submitter,
			&i.Pitch,
			&i.Tags,
			&i.PageCount,
			&i.Description,
			&i.ContentNotes,
			&i.CoverUrl,
			&i.Isbn,
			&i.MetadataSource,
			&i.MetadataID,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET title = ?, author = ?, submitter = ?, pitch = ?, tags = ?,
    page_count = ?, description = ?, content_notes = ?, cover_url = ?,
    isbn = ?, metadata_source = ?, metadata_id = ?, status = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateBookParams struct {
	Title          string         `json:"title"`
	Author         string         `json:"author"`
	Submitter      sql.NullString `json:"submitter"`
	Pitch          sql.NullString `json:"pitch"`
	Tags           sql.NullString `json:"tags"`
	PageCount      sql.NullInt64  `json:"page_count"`
	Description    sql.NullString `json:"description"`
	ContentNotes   sql.NullString `json:"content_notes"`
	CoverUrl       sql.NullString `json:"cover_url"`
	Isbn           sql.NullString `json:"isbn"`
	MetadataSource sql.NullString `json:"metadata_source"`
	MetadataID     sql.NullString `json:"metadata_id"`
	Status         string         `json:"status"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.ExecContext(ctx, updateBook,
		arg.Title,
		arg.Author,
		arg.Submitter,
		arg.Pitch,
		arg.Tags,
		arg.PageCount,
		arg.Description,
		arg.ContentNotes,
		arg.CoverUrl,
		arg.Isbn,
		arg.MetadataSource,
		arg.MetadataID,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateBookStatus = `-- name: UpdateBookStatus :exec
UPDATE books SET status = ?, deleted_at = CASE WHEN ? = 'archived' THEN CURRENT_TIMESTAMP ELSE deleted_at END
WHERE id = ?
`

type UpdateBookStatusParams struct {
	Status  string      `json:"status"`
	Column2 interface{} `json:"column_2"`
	ID      int64       `json:"id"`
}

func (q *Queries) UpdateBookStatus(ctx context.Context, arg UpdateBookStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBookStatus, arg.Status, arg.Column2, arg.ID)
	return err
}
